# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Parent' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Parent
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target 'ParentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ParentUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
